### ISSUE TITLE
Why do I not get the ReplitClient.js 

### ISSUE THREAD

**Issue by krishnavedula** [replit/ReplitClient.js#8]
I don't see the ReplitClient.js file either when I download or Clone

**Comment by amasad** [comment]
this is only a documentation repo

**Comment by ochen1** [comment]
@amasad May I ask where the ReplitClient.js file is hosted? Is it on NPM?

**Comment by amasad** [comment]
@ochen1 this project is dead. Check out https://github.com/replit/crosis
